version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.local
    volumes:
      - ./:/usr/src/app
      - node_modules_api:/src/node_modules
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}

    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db:
    driver: local
  node_modules_api:
