services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=server
      - MYSQL_PASSWORD=staging
      - MYSQL_ROOT_PASSWORD=devRO0T
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/db
volumes:
  mysql-data:
